name = "workers-airtable-form"
entry-point = "index.js"
type = "javascript"
compatibility_date = "2024-11-18"

# Wrangler configuration (wrangler v3.79.0^)
account_id = "20f3fe27a320b70fbb90d90ce5965695"
workers_dev = true

[observability.logs]
enabled = true

[vars]
AIRTABLE_BASE_ID = "appKWFjei6fzcRFFH"
AIRTABLE_TABLE_NAME = "Cloudflare Form"
FORM_URL = "https://form123.davidpacold.app"
SUBMIT_URL = "https://form123.davidpacold.app/success.html"
