name = "workers-airtable-form"
type = "javascript"

account_id = "20f3fe27a320b70fbb90d90ce5965695"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "keyVSV65QTLbpirdv"
AIRTABLE_TABLE_NAME = "Cloudflare Form Submissions"
FORM_URL = "https://workers-airtable-form.pages.dev"
